[package]
name = "cinp"
version = "1.0.0"
edition = "2021"


[dependencies]
http = "0.2"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
